Repository iMicknl/ha-nest-protect, pull requests merged in 2022-01, with the labels that each got.

#2 Pull bucket data from coordinator
  custom_components/nest_protect/__init__.py
  custom_components/nest_protect/binary_sensor.py
  custom_components/nest_protect/coordinator.py
  custom_components/nest_protect/entity.py
  custom_components/nest_protect/sensor.py
Labels: enhancement

#3 Handle result when 2factor is not enabled
  custom_components/nest_protect/pynest/client.py
Labels: bug

#6 Add issue templates
  .github/ISSUE_TEMPLATE/bug_report.yml
  .github/ISSUE_TEMPLATE/config.yml
  .github/ISSUE_TEMPLATE/feature_request.yml
Labels: enhancement, exclude-from-changelog

#14 Remove DataUpdateCoordinator (in preparation for long polling task)
  custom_components/nest_protect/__init__.py
  custom_components/nest_protect/binary_sensor.py
  custom_components/nest_protect/coordinator.py
  custom_components/nest_protect/entity.py
  custom_components/nest_protect/sensor.py
Labels: enhancement

#13 Add workflow for running tests on PR
  .github/workflows/pytest.yml
  pytest.ini
Labels: enhancement

#15 Fix brightness sensor and improve typing
  custom_components/nest_protect/sensor.py
Labels: enhancement
